development:
  adapter: async

test:
  adapter: test

production:
  adapter: async

  #adapter: redis
  #url: <%= ENV.fetch("REDIS_URL") { "redis://52.194.15.165/" } %>
  #channel_prefix: furima_29230_production
