development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  url: redis://52.194.15.165:3000
  channel_prefix: furima_29230_production
  
  # production:
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: furima_29230_production
